name: 🚀 Feature Request
description: Suggest an idea for improving hive
title: "[Feat]: "
labels: ["enhancement", "help wanted"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the current problem
      description: Provide a clear and concise description of what the problem is 
      placeholder: Write here...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution/feature you'd like
      description: Provide a clear and concise description of what you want to happen
      placeholder: Describe your proposal solution here...
    validations:
      required: true  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true